// Code generated by pigeon; DO NOT EDIT.

package parser

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"io/ioutil"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"

	"github.com/maniartech/uexl_go/ast"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "Input",
			pos:  position{line: 13, col: 1, offset: 150},
			expr: &actionExpr{
				pos: position{line: 13, col: 10, offset: 159},
				run: (*parser).callonInput1,
				expr: &seqExpr{
					pos: position{line: 13, col: 10, offset: 159},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 13, col: 10, offset: 159},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 13, col: 15, offset: 164},
								name: "Expr",
							},
						},
						&labeledExpr{
							pos:   position{line: 13, col: 20, offset: 169},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 13, col: 25, offset: 174},
								expr: &ruleRefExpr{
									pos:  position{line: 13, col: 25, offset: 174},
									name: "PipedExpr",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 13, col: 36, offset: 185},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Expr",
			pos:  position{line: 20, col: 1, offset: 354},
			expr: &actionExpr{
				pos: position{line: 20, col: 9, offset: 362},
				run: (*parser).callonExpr1,
				expr: &seqExpr{
					pos: position{line: 20, col: 9, offset: 362},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 20, col: 9, offset: 362},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 20, col: 11, offset: 364},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 20, col: 17, offset: 370},
								name: "Comp",
							},
						},
						&labeledExpr{
							pos:   position{line: 20, col: 22, offset: 375},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 20, col: 27, offset: 380},
								expr: &seqExpr{
									pos: position{line: 20, col: 29, offset: 382},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 20, col: 29, offset: 382},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 20, col: 31, offset: 384},
											name: "LogOp",
										},
										&ruleRefExpr{
											pos:  position{line: 20, col: 37, offset: 390},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 20, col: 39, offset: 392},
											name: "Comp",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 20, col: 47, offset: 400},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "Comp",
			pos:  position{line: 25, col: 1, offset: 514},
			expr: &actionExpr{
				pos: position{line: 25, col: 9, offset: 522},
				run: (*parser).callonComp1,
				expr: &seqExpr{
					pos: position{line: 25, col: 9, offset: 522},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 25, col: 9, offset: 522},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 25, col: 15, offset: 528},
								name: "Shift",
							},
						},
						&labeledExpr{
							pos:   position{line: 25, col: 21, offset: 534},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 25, col: 26, offset: 539},
								expr: &seqExpr{
									pos: position{line: 25, col: 28, offset: 541},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 25, col: 28, offset: 541},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 25, col: 30, offset: 543},
											name: "CmpOp",
										},
										&ruleRefExpr{
											pos:  position{line: 25, col: 36, offset: 549},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 25, col: 38, offset: 551},
											name: "Shift",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Bit",
			pos:  position{line: 30, col: 1, offset: 672},
			expr: &actionExpr{
				pos: position{line: 30, col: 8, offset: 679},
				run: (*parser).callonBit1,
				expr: &seqExpr{
					pos: position{line: 30, col: 8, offset: 679},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 30, col: 8, offset: 679},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 30, col: 14, offset: 685},
								name: "Shift",
							},
						},
						&labeledExpr{
							pos:   position{line: 30, col: 20, offset: 691},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 30, col: 25, offset: 696},
								expr: &seqExpr{
									pos: position{line: 30, col: 27, offset: 698},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 30, col: 27, offset: 698},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 30, col: 29, offset: 700},
											name: "BitOp",
										},
										&ruleRefExpr{
											pos:  position{line: 30, col: 35, offset: 706},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 30, col: 37, offset: 708},
											name: "Shift",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Shift",
			pos:  position{line: 35, col: 1, offset: 856},
			expr: &actionExpr{
				pos: position{line: 35, col: 10, offset: 865},
				run: (*parser).callonShift1,
				expr: &seqExpr{
					pos: position{line: 35, col: 10, offset: 865},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 35, col: 10, offset: 865},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 35, col: 16, offset: 871},
								name: "Sum",
							},
						},
						&labeledExpr{
							pos:   position{line: 35, col: 20, offset: 875},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 35, col: 26, offset: 881},
								expr: &seqExpr{
									pos: position{line: 35, col: 28, offset: 883},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 35, col: 28, offset: 883},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 35, col: 30, offset: 885},
											name: "ShiftOp",
										},
										&ruleRefExpr{
											pos:  position{line: 35, col: 38, offset: 893},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 35, col: 40, offset: 895},
											name: "Sum",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Sum",
			pos:  position{line: 40, col: 1, offset: 1043},
			expr: &actionExpr{
				pos: position{line: 40, col: 8, offset: 1050},
				run: (*parser).callonSum1,
				expr: &seqExpr{
					pos: position{line: 40, col: 8, offset: 1050},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 40, col: 8, offset: 1050},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 14, offset: 1056},
								name: "Mul",
							},
						},
						&labeledExpr{
							pos:   position{line: 40, col: 18, offset: 1060},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 40, col: 23, offset: 1065},
								expr: &seqExpr{
									pos: position{line: 40, col: 25, offset: 1067},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 40, col: 25, offset: 1067},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 40, col: 27, offset: 1069},
											name: "AddOp",
										},
										&ruleRefExpr{
											pos:  position{line: 40, col: 33, offset: 1075},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 40, col: 35, offset: 1077},
											name: "Mul",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Mul",
			pos:  position{line: 45, col: 1, offset: 1223},
			expr: &actionExpr{
				pos: position{line: 45, col: 8, offset: 1230},
				run: (*parser).callonMul1,
				expr: &seqExpr{
					pos: position{line: 45, col: 8, offset: 1230},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 45, col: 8, offset: 1230},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 45, col: 14, offset: 1236},
								name: "Mod",
							},
						},
						&labeledExpr{
							pos:   position{line: 45, col: 18, offset: 1240},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 45, col: 23, offset: 1245},
								expr: &seqExpr{
									pos: position{line: 45, col: 25, offset: 1247},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 45, col: 25, offset: 1247},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 45, col: 27, offset: 1249},
											name: "MulOp",
										},
										&ruleRefExpr{
											pos:  position{line: 45, col: 33, offset: 1255},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 45, col: 35, offset: 1257},
											name: "Mod",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Mod",
			pos:  position{line: 50, col: 1, offset: 1403},
			expr: &actionExpr{
				pos: position{line: 50, col: 8, offset: 1410},
				run: (*parser).callonMod1,
				expr: &seqExpr{
					pos: position{line: 50, col: 8, offset: 1410},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 50, col: 8, offset: 1410},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 50, col: 14, offset: 1416},
								name: "DotExpr",
							},
						},
						&labeledExpr{
							pos:   position{line: 50, col: 22, offset: 1424},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 50, col: 27, offset: 1429},
								expr: &seqExpr{
									pos: position{line: 50, col: 29, offset: 1431},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 50, col: 29, offset: 1431},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 50, col: 31, offset: 1433},
											name: "ModOp",
										},
										&ruleRefExpr{
											pos:  position{line: 50, col: 37, offset: 1439},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 50, col: 39, offset: 1441},
											name: "DotExpr",
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DotExpr",
			pos:  position{line: 57, col: 1, offset: 1653},
			expr: &actionExpr{
				pos: position{line: 57, col: 12, offset: 1664},
				run: (*parser).callonDotExpr1,
				expr: &seqExpr{
					pos: position{line: 57, col: 12, offset: 1664},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 57, col: 12, offset: 1664},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 57, col: 14, offset: 1666},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 57, col: 20, offset: 1672},
								name: "Factor",
							},
						},
						&labeledExpr{
							pos:   position{line: 57, col: 27, offset: 1679},
							label: "rest",
							expr: &zeroOrMoreExpr{
								pos: position{line: 57, col: 32, offset: 1684},
								expr: &seqExpr{
									pos: position{line: 57, col: 34, offset: 1686},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 57, col: 34, offset: 1686},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 57, col: 36, offset: 1688},
											name: "DotOp",
										},
										&ruleRefExpr{
											pos:  position{line: 57, col: 42, offset: 1694},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 57, col: 44, offset: 1696},
											name: "Identifier",
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 57, col: 58, offset: 1710},
							name: "_",
						},
					},
				},
			},
		},
		{
			name: "DotOp",
			pos:  position{line: 62, col: 1, offset: 1827},
			expr: &actionExpr{
				pos: position{line: 62, col: 10, offset: 1836},
				run: (*parser).callonDotOp1,
				expr: &litMatcher{
					pos:        position{line: 62, col: 10, offset: 1836},
					val:        ".",
					ignoreCase: false,
					want:       "\".\"",
				},
			},
		},
		{
			name: "Factor",
			pos:  position{line: 68, col: 1, offset: 1932},
			expr: &choiceExpr{
				pos: position{line: 68, col: 11, offset: 1942},
				alternatives: []interface{}{
					&actionExpr{
						pos: position{line: 68, col: 11, offset: 1942},
						run: (*parser).callonFactor2,
						expr: &seqExpr{
							pos: position{line: 68, col: 11, offset: 1942},
							exprs: []interface{}{
								&litMatcher{
									pos:        position{line: 68, col: 11, offset: 1942},
									val:        "(",
									ignoreCase: false,
									want:       "\"(\"",
								},
								&labeledExpr{
									pos:   position{line: 68, col: 15, offset: 1946},
									label: "expr",
									expr: &ruleRefExpr{
										pos:  position{line: 68, col: 20, offset: 1951},
										name: "Expr",
									},
								},
								&litMatcher{
									pos:        position{line: 68, col: 25, offset: 1956},
									val:        ")",
									ignoreCase: false,
									want:       "\")\"",
								},
							},
						},
					},
					&actionExpr{
						pos: position{line: 70, col: 5, offset: 1987},
						run: (*parser).callonFactor8,
						expr: &labeledExpr{
							pos:   position{line: 70, col: 5, offset: 1987},
							label: "value",
							expr: &ruleRefExpr{
								pos:  position{line: 70, col: 11, offset: 1993},
								name: "Value",
							},
						},
					},
				},
			},
		},
		{
			name: "PipedExpr",
			pos:  position{line: 76, col: 1, offset: 2098},
			expr: &actionExpr{
				pos: position{line: 76, col: 14, offset: 2111},
				run: (*parser).callonPipedExpr1,
				expr: &seqExpr{
					pos: position{line: 76, col: 14, offset: 2111},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 76, col: 14, offset: 2111},
							val:        "|",
							ignoreCase: false,
							want:       "\"|\"",
						},
						&labeledExpr{
							pos:   position{line: 76, col: 18, offset: 2115},
							label: "pipeType",
							expr: &zeroOrOneExpr{
								pos: position{line: 76, col: 27, offset: 2124},
								expr: &ruleRefExpr{
									pos:  position{line: 76, col: 27, offset: 2124},
									name: "PipeType",
								},
							},
						},
						&litMatcher{
							pos:        position{line: 76, col: 37, offset: 2134},
							val:        ":",
							ignoreCase: false,
							want:       "\":\"",
						},
						&labeledExpr{
							pos:   position{line: 76, col: 41, offset: 2138},
							label: "expr",
							expr: &ruleRefExpr{
								pos:  position{line: 76, col: 46, offset: 2143},
								name: "Expr",
							},
						},
					},
				},
			},
		},
		{
			name: "PipeType",
			pos:  position{line: 80, col: 1, offset: 2197},
			expr: &actionExpr{
				pos: position{line: 80, col: 13, offset: 2209},
				run: (*parser).callonPipeType1,
				expr: &oneOrMoreExpr{
					pos: position{line: 80, col: 13, offset: 2209},
					expr: &charClassMatcher{
						pos:        position{line: 80, col: 13, offset: 2209},
						val:        "[a-z]",
						ranges:     []rune{'a', 'z'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "AddOp",
			pos:  position{line: 86, col: 1, offset: 2319},
			expr: &actionExpr{
				pos: position{line: 86, col: 10, offset: 2328},
				run: (*parser).callonAddOp1,
				expr: &choiceExpr{
					pos: position{line: 86, col: 12, offset: 2330},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 86, col: 12, offset: 2330},
							val:        "+",
							ignoreCase: false,
							want:       "\"+\"",
						},
						&litMatcher{
							pos:        position{line: 86, col: 18, offset: 2336},
							val:        "-",
							ignoreCase: false,
							want:       "\"-\"",
						},
					},
				},
			},
		},
		{
			name: "MulOp",
			pos:  position{line: 90, col: 1, offset: 2380},
			expr: &actionExpr{
				pos: position{line: 90, col: 10, offset: 2389},
				run: (*parser).callonMulOp1,
				expr: &choiceExpr{
					pos: position{line: 90, col: 12, offset: 2391},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 90, col: 12, offset: 2391},
							val:        "*",
							ignoreCase: false,
							want:       "\"*\"",
						},
						&litMatcher{
							pos:        position{line: 90, col: 18, offset: 2397},
							val:        "/",
							ignoreCase: false,
							want:       "\"/\"",
						},
					},
				},
			},
		},
		{
			name: "ModOp",
			pos:  position{line: 94, col: 1, offset: 2441},
			expr: &actionExpr{
				pos: position{line: 94, col: 10, offset: 2450},
				run: (*parser).callonModOp1,
				expr: &litMatcher{
					pos:        position{line: 94, col: 12, offset: 2452},
					val:        "//",
					ignoreCase: false,
					want:       "\"//\"",
				},
			},
		},
		{
			name: "CmpOp",
			pos:  position{line: 98, col: 1, offset: 2497},
			expr: &actionExpr{
				pos: position{line: 98, col: 10, offset: 2506},
				run: (*parser).callonCmpOp1,
				expr: &choiceExpr{
					pos: position{line: 98, col: 12, offset: 2508},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 98, col: 12, offset: 2508},
							val:        "==",
							ignoreCase: false,
							want:       "\"==\"",
						},
						&litMatcher{
							pos:        position{line: 98, col: 19, offset: 2515},
							val:        "!=",
							ignoreCase: false,
							want:       "\"!=\"",
						},
						&litMatcher{
							pos:        position{line: 98, col: 26, offset: 2522},
							val:        "<=",
							ignoreCase: false,
							want:       "\"<=\"",
						},
						&litMatcher{
							pos:        position{line: 98, col: 33, offset: 2529},
							val:        ">=",
							ignoreCase: false,
							want:       "\">=\"",
						},
						&litMatcher{
							pos:        position{line: 98, col: 40, offset: 2536},
							val:        "<",
							ignoreCase: false,
							want:       "\"<\"",
						},
						&litMatcher{
							pos:        position{line: 98, col: 46, offset: 2542},
							val:        ">",
							ignoreCase: false,
							want:       "\">\"",
						},
					},
				},
			},
		},
		{
			name: "LogOp",
			pos:  position{line: 102, col: 1, offset: 2586},
			expr: &actionExpr{
				pos: position{line: 102, col: 10, offset: 2595},
				run: (*parser).callonLogOp1,
				expr: &choiceExpr{
					pos: position{line: 102, col: 12, offset: 2597},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 102, col: 12, offset: 2597},
							val:        "&&",
							ignoreCase: false,
							want:       "\"&&\"",
						},
						&litMatcher{
							pos:        position{line: 102, col: 19, offset: 2604},
							val:        "||",
							ignoreCase: false,
							want:       "\"||\"",
						},
					},
				},
			},
		},
		{
			name: "ShiftOp",
			pos:  position{line: 106, col: 1, offset: 2649},
			expr: &actionExpr{
				pos: position{line: 106, col: 12, offset: 2660},
				run: (*parser).callonShiftOp1,
				expr: &choiceExpr{
					pos: position{line: 106, col: 14, offset: 2662},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 106, col: 14, offset: 2662},
							val:        "<<",
							ignoreCase: false,
							want:       "\"<<\"",
						},
						&litMatcher{
							pos:        position{line: 106, col: 21, offset: 2669},
							val:        ">>",
							ignoreCase: false,
							want:       "\">>\"",
						},
					},
				},
			},
		},
		{
			name: "Value",
			pos:  position{line: 112, col: 1, offset: 2767},
			expr: &actionExpr{
				pos: position{line: 112, col: 10, offset: 2776},
				run: (*parser).callonValue1,
				expr: &labeledExpr{
					pos:   position{line: 112, col: 10, offset: 2776},
					label: "val",
					expr: &choiceExpr{
						pos: position{line: 112, col: 16, offset: 2782},
						alternatives: []interface{}{
							&ruleRefExpr{
								pos:  position{line: 112, col: 16, offset: 2782},
								name: "Number",
							},
							&ruleRefExpr{
								pos:  position{line: 112, col: 25, offset: 2791},
								name: "Bool",
							},
							&ruleRefExpr{
								pos:  position{line: 112, col: 32, offset: 2798},
								name: "Null",
							},
							&ruleRefExpr{
								pos:  position{line: 112, col: 39, offset: 2805},
								name: "String",
							},
							&ruleRefExpr{
								pos:  position{line: 112, col: 48, offset: 2814},
								name: "Array",
							},
							&ruleRefExpr{
								pos:  position{line: 112, col: 56, offset: 2822},
								name: "Object",
							},
							&ruleRefExpr{
								pos:  position{line: 112, col: 65, offset: 2831},
								name: "Function",
							},
							&ruleRefExpr{
								pos:  position{line: 112, col: 76, offset: 2842},
								name: "Identifier",
							},
						},
					},
				},
			},
		},
		{
			name: "Number",
			pos:  position{line: 118, col: 1, offset: 2938},
			expr: &actionExpr{
				pos: position{line: 118, col: 11, offset: 2948},
				run: (*parser).callonNumber1,
				expr: &seqExpr{
					pos: position{line: 118, col: 11, offset: 2948},
					exprs: []interface{}{
						&ruleRefExpr{
							pos:  position{line: 118, col: 11, offset: 2948},
							name: "Integer",
						},
						&zeroOrOneExpr{
							pos: position{line: 118, col: 19, offset: 2956},
							expr: &seqExpr{
								pos: position{line: 118, col: 21, offset: 2958},
								exprs: []interface{}{
									&litMatcher{
										pos:        position{line: 118, col: 21, offset: 2958},
										val:        ".",
										ignoreCase: false,
										want:       "\".\"",
									},
									&oneOrMoreExpr{
										pos: position{line: 118, col: 25, offset: 2962},
										expr: &ruleRefExpr{
											pos:  position{line: 118, col: 25, offset: 2962},
											name: "DecimalDigit",
										},
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 118, col: 42, offset: 2979},
							expr: &ruleRefExpr{
								pos:  position{line: 118, col: 42, offset: 2979},
								name: "Exponent",
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 124, col: 1, offset: 3089},
			expr: &actionExpr{
				pos: position{line: 124, col: 12, offset: 3100},
				run: (*parser).callonInteger1,
				expr: &seqExpr{
					pos: position{line: 124, col: 12, offset: 3100},
					exprs: []interface{}{
						&zeroOrOneExpr{
							pos: position{line: 124, col: 12, offset: 3100},
							expr: &charClassMatcher{
								pos:        position{line: 124, col: 12, offset: 3100},
								val:        "[+-]",
								chars:      []rune{'+', '-'},
								ignoreCase: false,
								inverted:   false,
							},
						},
						&oneOrMoreExpr{
							pos: position{line: 124, col: 18, offset: 3106},
							expr: &ruleRefExpr{
								pos:  position{line: 124, col: 18, offset: 3106},
								name: "DecimalDigit",
							},
						},
					},
				},
			},
		},
		{
			name: "Exponent",
			pos:  position{line: 128, col: 1, offset: 3167},
			expr: &seqExpr{
				pos: position{line: 128, col: 13, offset: 3179},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 128, col: 13, offset: 3179},
						val:        "e",
						ignoreCase: true,
						want:       "\"e\"i",
					},
					&zeroOrOneExpr{
						pos: position{line: 128, col: 18, offset: 3184},
						expr: &charClassMatcher{
							pos:        position{line: 128, col: 18, offset: 3184},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&oneOrMoreExpr{
						pos: position{line: 128, col: 24, offset: 3190},
						expr: &ruleRefExpr{
							pos:  position{line: 128, col: 24, offset: 3190},
							name: "DecimalDigit",
						},
					},
				},
			},
		},
		{
			name: "DecimalDigit",
			pos:  position{line: 130, col: 1, offset: 3207},
			expr: &charClassMatcher{
				pos:        position{line: 130, col: 17, offset: 3223},
				val:        "[0-9]",
				ranges:     []rune{'0', '9'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "HexDigit",
			pos:  position{line: 132, col: 1, offset: 3232},
			expr: &charClassMatcher{
				pos:        position{line: 132, col: 13, offset: 3244},
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
				inverted:   false,
			},
		},
		{
			name: "Bool",
			pos:  position{line: 136, col: 1, offset: 3312},
			expr: &actionExpr{
				pos: position{line: 136, col: 9, offset: 3320},
				run: (*parser).callonBool1,
				expr: &choiceExpr{
					pos: position{line: 136, col: 11, offset: 3322},
					alternatives: []interface{}{
						&litMatcher{
							pos:        position{line: 136, col: 11, offset: 3322},
							val:        "true",
							ignoreCase: false,
							want:       "\"true\"",
						},
						&litMatcher{
							pos:        position{line: 136, col: 20, offset: 3331},
							val:        "false",
							ignoreCase: false,
							want:       "\"false\"",
						},
					},
				},
			},
		},
		{
			name: "Null",
			pos:  position{line: 142, col: 1, offset: 3482},
			expr: &actionExpr{
				pos: position{line: 142, col: 9, offset: 3490},
				run: (*parser).callonNull1,
				expr: &litMatcher{
					pos:        position{line: 142, col: 11, offset: 3492},
					val:        "null",
					ignoreCase: false,
					want:       "\"null\"",
				},
			},
		},
		{
			name: "String",
			pos:  position{line: 148, col: 1, offset: 3647},
			expr: &choiceExpr{
				pos: position{line: 148, col: 12, offset: 3658},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 148, col: 12, offset: 3658},
						name: "DoubleQuoteString",
					},
					&ruleRefExpr{
						pos:  position{line: 148, col: 32, offset: 3678},
						name: "SingleQuoteString",
					},
					&ruleRefExpr{
						pos:  position{line: 148, col: 52, offset: 3698},
						name: "RawStringSingleQuote",
					},
					&ruleRefExpr{
						pos:  position{line: 148, col: 75, offset: 3721},
						name: "RawStringDoubleQuote",
					},
				},
			},
		},
		{
			name: "DoubleQuoteString",
			pos:  position{line: 150, col: 1, offset: 3746},
			expr: &actionExpr{
				pos: position{line: 150, col: 21, offset: 3768},
				run: (*parser).callonDoubleQuoteString1,
				expr: &seqExpr{
					pos: position{line: 150, col: 21, offset: 3768},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 150, col: 21, offset: 3768},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 150, col: 25, offset: 3772},
							expr: &choiceExpr{
								pos: position{line: 150, col: 27, offset: 3774},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 150, col: 27, offset: 3774},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 150, col: 27, offset: 3774},
												expr: &ruleRefExpr{
													pos:  position{line: 150, col: 28, offset: 3775},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 150, col: 40, offset: 3787,
											},
										},
									},
									&seqExpr{
										pos: position{line: 150, col: 44, offset: 3791},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 150, col: 44, offset: 3791},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 150, col: 49, offset: 3796},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 150, col: 67, offset: 3814},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "SingleQuoteString",
			pos:  position{line: 154, col: 1, offset: 3899},
			expr: &actionExpr{
				pos: position{line: 154, col: 22, offset: 3920},
				run: (*parser).callonSingleQuoteString1,
				expr: &seqExpr{
					pos: position{line: 154, col: 22, offset: 3920},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 154, col: 22, offset: 3920},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 154, col: 27, offset: 3925},
							expr: &choiceExpr{
								pos: position{line: 154, col: 29, offset: 3927},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 154, col: 29, offset: 3927},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 154, col: 29, offset: 3927},
												expr: &ruleRefExpr{
													pos:  position{line: 154, col: 30, offset: 3928},
													name: "EscapedChar",
												},
											},
											&anyMatcher{
												line: 154, col: 42, offset: 3940,
											},
										},
									},
									&seqExpr{
										pos: position{line: 154, col: 46, offset: 3944},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 154, col: 46, offset: 3944},
												val:        "\\",
												ignoreCase: false,
												want:       "\"\\\\\"",
											},
											&ruleRefExpr{
												pos:  position{line: 154, col: 51, offset: 3949},
												name: "EscapeSequence",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 154, col: 69, offset: 3967},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
					},
				},
			},
		},
		{
			name: "RawStringSingleQuote",
			pos:  position{line: 162, col: 1, offset: 4304},
			expr: &actionExpr{
				pos: position{line: 162, col: 25, offset: 4328},
				run: (*parser).callonRawStringSingleQuote1,
				expr: &seqExpr{
					pos: position{line: 162, col: 25, offset: 4328},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 162, col: 25, offset: 4328},
							val:        "r",
							ignoreCase: false,
							want:       "\"r\"",
						},
						&litMatcher{
							pos:        position{line: 162, col: 29, offset: 4332},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 162, col: 34, offset: 4337},
							expr: &choiceExpr{
								pos: position{line: 162, col: 36, offset: 4339},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 162, col: 36, offset: 4339},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 162, col: 36, offset: 4339},
												expr: &litMatcher{
													pos:        position{line: 162, col: 37, offset: 4340},
													val:        "'",
													ignoreCase: false,
													want:       "\"'\"",
												},
											},
											&anyMatcher{
												line: 162, col: 42, offset: 4345,
											},
										},
									},
									&seqExpr{
										pos: position{line: 162, col: 46, offset: 4349},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 162, col: 46, offset: 4349},
												val:        "'",
												ignoreCase: false,
												want:       "\"'\"",
											},
											&litMatcher{
												pos:        position{line: 162, col: 51, offset: 4354},
												val:        "'",
												ignoreCase: false,
												want:       "\"'\"",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 162, col: 59, offset: 4362},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
					},
				},
			},
		},
		{
			name: "RawStringDoubleQuote",
			pos:  position{line: 166, col: 1, offset: 4448},
			expr: &actionExpr{
				pos: position{line: 166, col: 25, offset: 4472},
				run: (*parser).callonRawStringDoubleQuote1,
				expr: &seqExpr{
					pos: position{line: 166, col: 25, offset: 4472},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 166, col: 25, offset: 4472},
							val:        "r",
							ignoreCase: false,
							want:       "\"r\"",
						},
						&litMatcher{
							pos:        position{line: 166, col: 29, offset: 4476},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 166, col: 33, offset: 4480},
							expr: &choiceExpr{
								pos: position{line: 166, col: 35, offset: 4482},
								alternatives: []interface{}{
									&seqExpr{
										pos: position{line: 166, col: 35, offset: 4482},
										exprs: []interface{}{
											&notExpr{
												pos: position{line: 166, col: 35, offset: 4482},
												expr: &litMatcher{
													pos:        position{line: 166, col: 36, offset: 4483},
													val:        "\"",
													ignoreCase: false,
													want:       "\"\\\"\"",
												},
											},
											&anyMatcher{
												line: 166, col: 40, offset: 4487,
											},
										},
									},
									&seqExpr{
										pos: position{line: 166, col: 44, offset: 4491},
										exprs: []interface{}{
											&litMatcher{
												pos:        position{line: 166, col: 44, offset: 4491},
												val:        "\"",
												ignoreCase: false,
												want:       "\"\\\"\"",
											},
											&litMatcher{
												pos:        position{line: 166, col: 48, offset: 4495},
												val:        "\"",
												ignoreCase: false,
												want:       "\"\\\"\"",
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 166, col: 55, offset: 4502},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "EscapedChar",
			pos:  position{line: 170, col: 1, offset: 4587},
			expr: &charClassMatcher{
				pos:        position{line: 170, col: 16, offset: 4602},
				val:        "[\\x00-\\x1f\"'\\\\]",
				chars:      []rune{'"', '\'', '\\'},
				ranges:     []rune{'\x00', '\x1f'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "EscapeSequence",
			pos:  position{line: 172, col: 1, offset: 4621},
			expr: &choiceExpr{
				pos: position{line: 172, col: 19, offset: 4639},
				alternatives: []interface{}{
					&ruleRefExpr{
						pos:  position{line: 172, col: 19, offset: 4639},
						name: "SingleCharEscape",
					},
					&ruleRefExpr{
						pos:  position{line: 172, col: 38, offset: 4658},
						name: "UnicodeEscape",
					},
				},
			},
		},
		{
			name: "SingleCharEscape",
			pos:  position{line: 174, col: 1, offset: 4675},
			expr: &charClassMatcher{
				pos:        position{line: 174, col: 21, offset: 4695},
				val:        "[\"\\\\/bfnrt]",
				chars:      []rune{'"', '\\', '/', 'b', 'f', 'n', 'r', 't'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "UnicodeEscape",
			pos:  position{line: 176, col: 1, offset: 4710},
			expr: &seqExpr{
				pos: position{line: 176, col: 18, offset: 4727},
				exprs: []interface{}{
					&litMatcher{
						pos:        position{line: 176, col: 18, offset: 4727},
						val:        "u",
						ignoreCase: false,
						want:       "\"u\"",
					},
					&ruleRefExpr{
						pos:  position{line: 176, col: 22, offset: 4731},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 176, col: 31, offset: 4740},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 176, col: 40, offset: 4749},
						name: "HexDigit",
					},
					&ruleRefExpr{
						pos:  position{line: 176, col: 49, offset: 4758},
						name: "HexDigit",
					},
				},
			},
		},
		{
			name: "Array",
			pos:  position{line: 180, col: 1, offset: 4825},
			expr: &actionExpr{
				pos: position{line: 180, col: 10, offset: 4834},
				run: (*parser).callonArray1,
				expr: &seqExpr{
					pos: position{line: 180, col: 10, offset: 4834},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 180, col: 10, offset: 4834},
							val:        "[",
							ignoreCase: false,
							want:       "\"[\"",
						},
						&ruleRefExpr{
							pos:  position{line: 180, col: 14, offset: 4838},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 180, col: 16, offset: 4840},
							label: "vals",
							expr: &zeroOrOneExpr{
								pos: position{line: 180, col: 21, offset: 4845},
								expr: &seqExpr{
									pos: position{line: 180, col: 23, offset: 4847},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 180, col: 23, offset: 4847},
											name: "Expr",
										},
										&zeroOrMoreExpr{
											pos: position{line: 180, col: 28, offset: 4852},
											expr: &seqExpr{
												pos: position{line: 180, col: 30, offset: 4854},
												exprs: []interface{}{
													&litMatcher{
														pos:        position{line: 180, col: 30, offset: 4854},
														val:        ",",
														ignoreCase: false,
														want:       "\",\"",
													},
													&ruleRefExpr{
														pos:  position{line: 180, col: 34, offset: 4858},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 180, col: 36, offset: 4860},
														name: "Expr",
													},
												},
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 180, col: 47, offset: 4871},
							val:        "]",
							ignoreCase: false,
							want:       "\"]\"",
						},
					},
				},
			},
		},
		{
			name: "Object",
			pos:  position{line: 184, col: 1, offset: 4957},
			expr: &actionExpr{
				pos: position{line: 184, col: 11, offset: 4967},
				run: (*parser).callonObject1,
				expr: &seqExpr{
					pos: position{line: 184, col: 11, offset: 4967},
					exprs: []interface{}{
						&litMatcher{
							pos:        position{line: 184, col: 11, offset: 4967},
							val:        "{",
							ignoreCase: false,
							want:       "\"{\"",
						},
						&ruleRefExpr{
							pos:  position{line: 184, col: 15, offset: 4971},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 184, col: 17, offset: 4973},
							label: "vals",
							expr: &zeroOrOneExpr{
								pos: position{line: 184, col: 22, offset: 4978},
								expr: &seqExpr{
									pos: position{line: 184, col: 24, offset: 4980},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 184, col: 24, offset: 4980},
											name: "String",
										},
										&ruleRefExpr{
											pos:  position{line: 184, col: 31, offset: 4987},
											name: "_",
										},
										&litMatcher{
											pos:        position{line: 184, col: 33, offset: 4989},
											val:        ":",
											ignoreCase: false,
											want:       "\":\"",
										},
										&ruleRefExpr{
											pos:  position{line: 184, col: 37, offset: 4993},
											name: "_",
										},
										&ruleRefExpr{
											pos:  position{line: 184, col: 39, offset: 4995},
											name: "Expr",
										},
										&zeroOrMoreExpr{
											pos: position{line: 184, col: 44, offset: 5000},
											expr: &seqExpr{
												pos: position{line: 184, col: 46, offset: 5002},
												exprs: []interface{}{
													&litMatcher{
														pos:        position{line: 184, col: 46, offset: 5002},
														val:        ",",
														ignoreCase: false,
														want:       "\",\"",
													},
													&ruleRefExpr{
														pos:  position{line: 184, col: 50, offset: 5006},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 184, col: 52, offset: 5008},
														name: "String",
													},
													&ruleRefExpr{
														pos:  position{line: 184, col: 59, offset: 5015},
														name: "_",
													},
													&litMatcher{
														pos:        position{line: 184, col: 61, offset: 5017},
														val:        ":",
														ignoreCase: false,
														want:       "\":\"",
													},
													&ruleRefExpr{
														pos:  position{line: 184, col: 65, offset: 5021},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 184, col: 67, offset: 5023},
														name: "Expr",
													},
												},
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 184, col: 78, offset: 5034},
							val:        "}",
							ignoreCase: false,
							want:       "\"}\"",
						},
					},
				},
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 191, col: 1, offset: 5221},
			expr: &actionExpr{
				pos: position{line: 191, col: 15, offset: 5235},
				run: (*parser).callonIdentifier1,
				expr: &zeroOrMoreExpr{
					pos: position{line: 191, col: 15, offset: 5235},
					expr: &ruleRefExpr{
						pos:  position{line: 191, col: 15, offset: 5235},
						name: "IdSet",
					},
				},
			},
		},
		{
			name: "IdSet",
			pos:  position{line: 195, col: 1, offset: 5335},
			expr: &actionExpr{
				pos: position{line: 195, col: 10, offset: 5344},
				run: (*parser).callonIdSet1,
				expr: &oneOrMoreExpr{
					pos: position{line: 195, col: 10, offset: 5344},
					expr: &charClassMatcher{
						pos:        position{line: 195, col: 10, offset: 5344},
						val:        "[a-zA-Z0-9$_@]",
						chars:      []rune{'$', '_', '@'},
						ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
						ignoreCase: false,
						inverted:   false,
					},
				},
			},
		},
		{
			name: "Function",
			pos:  position{line: 201, col: 1, offset: 5456},
			expr: &actionExpr{
				pos: position{line: 201, col: 13, offset: 5468},
				run: (*parser).callonFunction1,
				expr: &seqExpr{
					pos: position{line: 201, col: 13, offset: 5468},
					exprs: []interface{}{
						&labeledExpr{
							pos:   position{line: 201, col: 13, offset: 5468},
							label: "fn",
							expr: &oneOrMoreExpr{
								pos: position{line: 201, col: 16, offset: 5471},
								expr: &ruleRefExpr{
									pos:  position{line: 201, col: 16, offset: 5471},
									name: "IdSet",
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 201, col: 23, offset: 5478},
							name: "_",
						},
						&litMatcher{
							pos:        position{line: 201, col: 25, offset: 5480},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&ruleRefExpr{
							pos:  position{line: 201, col: 29, offset: 5484},
							name: "_",
						},
						&labeledExpr{
							pos:   position{line: 201, col: 31, offset: 5486},
							label: "params",
							expr: &zeroOrOneExpr{
								pos: position{line: 201, col: 38, offset: 5493},
								expr: &seqExpr{
									pos: position{line: 201, col: 40, offset: 5495},
									exprs: []interface{}{
										&ruleRefExpr{
											pos:  position{line: 201, col: 40, offset: 5495},
											name: "Expr",
										},
										&zeroOrMoreExpr{
											pos: position{line: 201, col: 45, offset: 5500},
											expr: &seqExpr{
												pos: position{line: 201, col: 47, offset: 5502},
												exprs: []interface{}{
													&litMatcher{
														pos:        position{line: 201, col: 47, offset: 5502},
														val:        ",",
														ignoreCase: false,
														want:       "\",\"",
													},
													&ruleRefExpr{
														pos:  position{line: 201, col: 51, offset: 5506},
														name: "_",
													},
													&ruleRefExpr{
														pos:  position{line: 201, col: 53, offset: 5508},
														name: "Expr",
													},
												},
											},
										},
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 201, col: 64, offset: 5519},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name:        "_",
			displayName: "\"whitespace\"",
			pos:         position{line: 207, col: 1, offset: 5681},
			expr: &zeroOrMoreExpr{
				pos: position{line: 207, col: 19, offset: 5699},
				expr: &charClassMatcher{
					pos:        position{line: 207, col: 19, offset: 5699},
					val:        "[ \\n\\t\\r]",
					chars:      []rune{' ', '\n', '\t', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 211, col: 1, offset: 5766},
			expr: &notExpr{
				pos: position{line: 211, col: 8, offset: 5773},
				expr: &anyMatcher{
					line: 211, col: 9, offset: 5774,
				},
			},
		},
	},
}

func (c *current) onInput1(expr, rest interface{}) (interface{}, error) {

	// Input
	return parseInput(string(c.text), expr, rest, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonInput1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInput1(stack["expr"], stack["rest"])
}

func (c *current) onExpr1(first, rest interface{}) (interface{}, error) {

	// Expr:
	return parseExpression(string(c.text), first, rest, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onExpr1(stack["first"], stack["rest"])
}

func (c *current) onComp1(first, rest interface{}) (interface{}, error) {

	// Comp:
	return parseExpression(string(c.text), first, rest, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonComp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onComp1(stack["first"], stack["rest"])
}

func (c *current) onBit1(first, rest interface{}) (interface{}, error) {

	// fmt.Println("Bit:", first, rest)
	return parseExpression(string(c.text), first, rest, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonBit1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBit1(stack["first"], stack["rest"])
}

func (c *current) onShift1(first, rest interface{}) (interface{}, error) {

	// fmt.Println("Shift:", first, rest)
	return parseExpression(string(c.text), first, rest, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonShift1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onShift1(stack["first"], stack["rest"])
}

func (c *current) onSum1(first, rest interface{}) (interface{}, error) {

	// fmt.Println("Sum:", first, rest)
	return parseExpression(string(c.text), first, rest, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonSum1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSum1(stack["first"], stack["rest"])
}

func (c *current) onMul1(first, rest interface{}) (interface{}, error) {

	// fmt.Println("Mul:", first, rest)
	return parseExpression(string(c.text), first, rest, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonMul1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMul1(stack["first"], stack["rest"])
}

func (c *current) onMod1(first, rest interface{}) (interface{}, error) {

	// fmt.Println("Mod:", first, rest)
	return parseExpression(string(c.text), first, rest, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonMod1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMod1(stack["first"], stack["rest"])
}

func (c *current) onDotExpr1(first, rest interface{}) (interface{}, error) {

	// Expr:
	return parseDotExpression(string(c.text), first, rest, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonDotExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDotExpr1(stack["first"], stack["rest"])
}

func (c *current) onDotOp1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonDotOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDotOp1()
}

func (c *current) onFactor2(expr interface{}) (interface{}, error) {

	return expr, nil
}

func (p *parser) callonFactor2() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFactor2(stack["expr"])
}

func (c *current) onFactor8(value interface{}) (interface{}, error) {

	return value, nil
}

func (p *parser) callonFactor8() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFactor8(stack["value"])
}

func (c *current) onPipedExpr1(pipeType, expr interface{}) (interface{}, error) {

	return parsePipe(pipeType, expr), nil
}

func (p *parser) callonPipedExpr1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPipedExpr1(stack["pipeType"], stack["expr"])
}

func (c *current) onPipeType1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonPipeType1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onPipeType1()
}

func (c *current) onAddOp1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonAddOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onAddOp1()
}

func (c *current) onMulOp1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonMulOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onMulOp1()
}

func (c *current) onModOp1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonModOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onModOp1()
}

func (c *current) onCmpOp1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonCmpOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCmpOp1()
}

func (c *current) onLogOp1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonLogOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLogOp1()
}

func (c *current) onShiftOp1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonShiftOp1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onShiftOp1()
}

func (c *current) onValue1(val interface{}) (interface{}, error) {

	return val, nil
}

func (p *parser) callonValue1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onValue1(stack["val"])
}

func (c *current) onNumber1() (interface{}, error) {

	return ast.NewNumberNode(
		string(c.text), c.pos.offset, c.pos.line, c.pos.col,
	)
}

func (p *parser) callonNumber1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNumber1()
}

func (c *current) onInteger1() (interface{}, error) {

	return strconv.Atoi(string(c.text))
}

func (p *parser) callonInteger1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onInteger1()
}

func (c *current) onBool1() (interface{}, error) {

	return ast.NewBooleanNode(string(c.text), c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonBool1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBool1()
}

func (c *current) onNull1() (interface{}, error) {

	return ast.NewNullNode(string(c.text), c.pos.offset, c.pos.line, c.pos.col), nil
}

func (p *parser) callonNull1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNull1()
}

func (c *current) onDoubleQuoteString1() (interface{}, error) {

	return ast.NewStringNode(c.text, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonDoubleQuoteString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onDoubleQuoteString1()
}

func (c *current) onSingleQuoteString1() (interface{}, error) {

	return ast.NewStringNode(c.text, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonSingleQuoteString1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSingleQuoteString1()
}

func (c *current) onRawStringSingleQuote1() (interface{}, error) {

	return ast.NewStringNode(c.text, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonRawStringSingleQuote1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRawStringSingleQuote1()
}

func (c *current) onRawStringDoubleQuote1() (interface{}, error) {

	return ast.NewStringNode(c.text, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonRawStringDoubleQuote1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onRawStringDoubleQuote1()
}

func (c *current) onArray1(vals interface{}) (interface{}, error) {

	return parseArray(vals, c.text, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonArray1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onArray1(stack["vals"])
}

func (c *current) onObject1(vals interface{}) (interface{}, error) {

	return parseObject(vals, c.text, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonObject1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onObject1(stack["vals"])
}

func (c *current) onIdentifier1() (interface{}, error) {

	return ast.NewIdentifierNode(string(c.text), c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonIdentifier1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdentifier1()
}

func (c *current) onIdSet1() (interface{}, error) {

	return string(c.text), nil
}

func (p *parser) callonIdSet1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onIdSet1()
}

func (c *current) onFunction1(fn, params interface{}) (interface{}, error) {

	return parseFunction(string(c.text), fn, params, c.pos.offset, c.pos.line, c.pos.col)
}

func (p *parser) callonFunction1() (interface{}, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFunction1(stack["fn"], stack["params"])
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expresssions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value interface{}) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i interface{}, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (interface{}, error) {
	b, err := ioutil.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (interface{}, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]interface{}

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        interface{}
}

type choiceExpr struct {
	pos          position
	alternatives []interface{}
}

type actionExpr struct {
	pos  position
	expr interface{}
	run  func(*parser) (interface{}, error)
}

type recoveryExpr struct {
	pos          position
	expr         interface{}
	recoverExpr  interface{}
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []interface{}
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  interface{}
}

type expr struct {
	pos  position
	expr interface{}
}

type andExpr expr
type notExpr expr
type zeroOrOneExpr expr
type zeroOrMoreExpr expr
type oneOrMoreExpr expr

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   interface{}
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[interface{}]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]interface{}
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]interface{}
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]interface{})
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr interface{}) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]interface{}, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) in(s string) string {
	p.depth++
	return p.print(strings.Repeat(" ", p.depth)+">", s)
}

func (p *parser) out(s string) string {
	p.depth--
	return p.print(strings.Repeat(" ", p.depth)+"<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() interface{}
}

var statePool = &sync.Pool{
	New: func() interface{} { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node interface{}) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node interface{}, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[interface{}]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[interface{}]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val interface{}, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRule(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRule(rule *rule) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}

	if p.memoize {
		res, ok := p.getMemoized(rule)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
	}

	start := p.pt
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExpr(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}

	if p.memoize {
		p.setMemoized(start, rule, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr interface{}) (interface{}, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val interface{}
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExpr(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.print(strings.Repeat(" ", p.depth)+"MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExpr(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExpr(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExpr(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExpr(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExpr(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRule(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]interface{}, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExpr(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExpr(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []interface{}

	for {
		p.pushV()
		val, ok := p.parseExpr(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (interface{}, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExpr(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
